### ISSUE TITLE
Steam OS 3.5 long boot time

### ISSUE THREAD

**Issue by eHerbaciarz** [ryanrudolfoba/SteamDeck-Clover-dualboot#27]
I use Clover for dual-boot (SteamOS 3.5 and Windows 10) - https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot (release 15.10.2023)
And I noticed that SteamOS loads much slower due to Clover - ~30 seconds to even over one minute. Windows 10 starts immediately.
If I boot SteamOS directly from UEFI (Vol - + power button), the system starts almost immediately.

What could be causing the long startup time?

**Comment by ryanrudolfoba** [comment]
We have an identical setup - WIN10 amd SteamOS 3.5

Boot SteamOS and then go to desktop mode.

Open konsole terminal and type this command -

systemd-analyze time

It will show a breakdown of how long it takes to boot. My output is this -

5.50 - firmware

4.87 - loader

1.84 - kernel

5.95 - userspace

Add all of that and you get your boot time. Mine is 18.06seconds.

With that said i find the boot times inconsistent. Even without Clover sometimes SteamOS takes a while to load getting stuck on a blank screen. I don't think this is caused by the Clover script itself. The Clover script that runs automatically at startup only takes milliseconds to run.

![PXL_20231005_170848749 MP](https://github.com/ryanrudolfoba/SteamDeck-Clover-dualboot/assets/98122529/2053f8d9-f3bb-4175-a3b9-6d3358d56600)

**Comment by hartojodylan** [comment]
I have a similar issue on Steam OS 3.5, Bios 118.

Steps to reproduce for me:
1. Boot into windows
2. Restart
3. Boot into steam OS
4. Steam OS takes a really long time to boot or doesn't boot at all

Fix:
1. Force power down by holding the power button
2. Boot again into Steam OS
3. Steam OS boots at normal (fast) speed

I'm not sure what's causing it, if I was using Steam OS before the shutdown and use Steam OS again, the long boot doesn't happen.

Maybe important:
- Undervolted steam deck

**Comment by hartojodylan** [comment]
Where can I find the sanity check systemd script? I'll try to code review it and comment here if I find something that could possibly be related

**Comment by ryanrudolfoba** [comment]
@hartojodylan 
Please check my previous reply and use systemd-analyze time and compare the output.

The systemd script is located here -

/etc/systemd/system/clover-bootmanager.sh

**Comment by ryanrudolfoba** [comment]
havent heard back so i'll be closing this issue.

**Comment by DavidinCT** [comment]
Same issue here, seems like it hangs forever booting

Mine are
7.225s - firmware

3.43s - loader

1.99s- kernel

5.95 - userspace

= 19.053 loading.

Takes forever to boot in SteamOS, Windows is like instant

**Comment by DavidinCT** [comment]
I'll try your new REPO and see, I'll report back with results...
